apply plugin: 'com.android.application'

android {
    namespace 'veg.mediacapture.sdk.test.demo'
    compileSdkVersion 34
    buildToolsVersion "34.0.0"

    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 34
    }

sourceSets {
    main {
        java {
            srcDirs = ["../MediaStreamTest/src"]
        }
	manifest{ 
            srcFile '../MediaStreamTest/AndroidManifest.xml'
        }
        res {
            srcDir '../MediaStreamTest/res'
        }
        assets {
            srcDir '../MediaStreamTest/assets'
        }
    }
}

}

dependencies {
}


